### ISSUE TITLE
Wiki Contributions

### ISSUE THREAD

**Issue by meaudotme** [Wittmaxi/ZENeural#2]
Salut!

I like this project and I hope it gets big at some point. I wanted to contribute to the Wiki, so I cloned it and made a few changes. Please, review them and maybe pull them in if you like them.

The repo is [located there](https://github.com/R4meau/ZENeural-wiki). And [here are the changes](https://github.com/R4meau/ZENeural-wiki/commit/beb6a108379917ccac8514b188ebfe61c116aca5) I made.

Cheers.

**Comment by Wittmaxi** [comment]
Thank you a lot! I have copied your edits into my wiki pages :)

-Maximilian
